episodeLength: 25
compass: true
weather: false
map:
    size: 2000
    wall:
        height: 128
        block: 7
daylightCycle:
    do: false
    time: 6000
allow-reconnect: false
scoreboard: CartoonCraft UHC
kick-on-death:
    kick: true
    time: 30